In [1]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv(r"countries_dataset.csv")
df

,country,countrylong,currency,capital city,region,continent,latitude,longitude,agriculture land,forestarea,land ares,rural land,urban land,population,democratic score,political leader
0,India,Republic of India,Indian Rupee,New Delhi,Southern Asia,Asia,20.5937,78.9629,2973190,720160,2973190,2090800,88300,1438069596,7.18,Narendra Modi
1,United States,United States of America,US Dollar,"Washington, D.C.",Northern America,North America,37.0902,-95.7129,4076730,3100950,9147420,6740000,268000,340110988,7.85,Donald Trump
2,Canada,Canada,Canadian Dollar,Ottawa,Northern America,North America,56.1304,-106.3468,517900,3470000,9093510,8080000,160000,40105275,8.69,Mark Carney
3,United Kingdom,United Kingdom of Great Britain and Northern I...,Pound Sterling,London,Northern Europe,Europe,55.3781,-3.4360,172000,317000,241930,160000,19000,69226000,8.31,Keir Starmer
4,France,French Republic,Euro,Paris,Western Europe,Europe,46.2276,2.2137,287000,172000,547557,310000,28000,66650000,8.07,Emmanuel Macron
5,Germany,Federal Republic of Germany,Euro,Berlin,Western Europe,Europe,51.1657,10.4515,165000,114000,348560,210000,26000,83500000,8.68,Friedrich Merz
6,Italy,Italian Republic,Euro,Rome,Southern Europe,Europe,41.8719,12.5674,124000,95000,294140,145000,12000,58900000,7.69,Giorgia Meloni
7,Spain,Kingdom of Spain,Euro,Madrid,Southern Europe,Europe,40.4637,-3.7492,238000,185000,499556,250000,15000,49000000,8.07,Pedro Sánchez
8,Brazil,Federative Republic of Brazil,Brazilian Real,Brasília,South America,South America,-14.2350,-51.9253,2820000,4966200,8358140,6890000,300000,212583750,6.49,Luiz Inácio Lula da Silva
9,Mexico,United Mexican States,Mexican Peso,Mexico City,Central America,North America,23.6345,-102.5528,963000,656000,1943950,1440000,95000,131946900,5.73,Claudia Sheinbaum
10,Argentina,Argentine Republic,Argentine Peso,Buenos Aires,South America,South America,-38.4161,-63.6167,1080000,945000,2736690,2050000,100000,45851000,6.62,Javier Milei
11,Australia,Commonwealth of Australia,Australian Dollar,Canberra,Australia and New Zealand,Oceania,-25.2744,133.7751,3630000,1340000,7682300,6400000,220000,27230000,8.66,Anthony Albanese
12,Japan,Japan,Japanese Yen,Tokyo,Eastern Asia,Asia,36.2048,138.2529,43700,249000,364500,250000,13000,123300000,8.33,Shigeru Ishiba
13,South Korea,Republic of Korea,South Korean Won,Seoul,Eastern Asia,Asia,35.9078,127.7669,16400,62900,97600,54000,9000,51710000,8.09,NaN
14,China,People's Republic of China,Chinese Yuan,Beijing,Eastern Asia,Asia,35.8617,104.1954,5280000,2190000,9424700,6500000,300000,1408280000,2.94,Xi Jinping
15,Indonesia,Republic of Indonesia,Indonesian Rupiah,Jakarta,South-eastern Asia,Asia,-0.7893,113.9213,1560000,921000,1877519,1240000,65000,283500000,6.44,Prabowo Subianto
16,Thailand,Kingdom of Thailand,Thai Baht,Bangkok,South-eastern Asia,Asia,15.8700,100.9925,221000,163000,510890,350000,22000,71620000,6.32,Paetongtarn Shinawatra
17,Vietnam,Socialist Republic of Viet Nam,Vietnamese Dong,Hanoi,South-eastern Asia,Asia,14.0583,108.2772,123000,149000,310070,190000,10000,101300000,3.08,Tô Lâm
18,Saudi Arabia,Kingdom of Saudi Arabia,Saudi Riyal,Riyadh,Western Asia,Asia,23.8859,45.0792,173000,9770,2149690,2040000,6000,34500000,2.08,Mohammed bin Salman
19,United Arab Emirates,United Arab Emirates,UAE Dirham,Abu Dhabi,Western Asia,Asia,23.4241,53.8478,4200,300,71020,65000,2500,11294000,3.05,Mohamed bin Zayed Al Nahyan
20,South Africa,Republic of South Africa,South African Rand,Pretoria,Southern Africa,Africa,-30.5595,22.9375,963000,289000,1213090,1030000,25000,64007000,7.05,Cyril Ramaphosa
21,Egypt,Arab Republic of Egypt,Egyptian Pound,Cairo,Northern Africa,Africa,26.8206,30.8025,31000,700,995450,940000,5000,118370000,2.98,Abdel Fattah el-Sisi
22,Nigeria,Federal Republic of Nigeria,Nigerian Naira,Abuja,Western Africa,Africa,9.0820,8.6753,690000,232000,910770,730000,20000,237528000,4.44,Bola Tinubu
23,Kenya,Republic of Kenya,Kenyan Shilling,Nairobi,Eastern Africa,Africa,-0.0236,37.9062,276000,37700,569140,460000,13000,56433000,5.88,William Ruto
24,Morocco,Kingdom of Morocco,Moroccan Dirham,Rabat,Northern Africa,Africa,31.7917,-7.0926,300000,57000,446300,350000,10000,38380000,5.04,Aziz Akhannouch
25,Turkey,Republic of Türkiye,Turkish Lira,Ankara,Western Asia,Asia,38.9637,35.2433,386000,223000,769630,580000,30000,87770000,4.33,Recep Tayyip Erdoğan
26,Russia,Russian Federation,Russian Ruble,Moscow,Eastern Europe,Europe,61.5240,105.3188,2150000,8150000,16376870,12200000,150000,143957000,2.94,Vladimir Putin
27,Ukraine,Ukraine,Ukrainian Hryvnia,Kyiv,Eastern Europe,Europe,48.3794,31.1656,413000,96700,579320,400000,12000,38000000,5.73,Volodymyr Zelenskyy
28,Poland,Republic of Poland,Polish Zloty,Warsaw,Eastern Europe,Europe,51.9194,19.1451,180000,95000,311888,200000,16000,36600000,8.00,Donald Tusk
29,Netherlands,Kingdom of the Netherlands,Euro,Amsterdam,Western Europe,Europe,52.1326,5.2913,18100,3700,33670,16000,1500,17900000,8.89,Dick Schoof
30,Sweden,Kingdom of Sweden,Swedish Krona,Stockholm,Northern Europe,Europe,60.1282,18.6435,26500,280000,407284,330000,7000,10600000,9.39,Ulf Kristersson
31,Norway,Kingdom of Norway,Norwegian Krone,Oslo,Northern Europe,Europe,60.4720,8.4689,11300,121000,364270,290000,5000,5600000,9.81,Jonas Gahr Støre
32,Switzerland,Swiss Confederation,Swiss Franc,Bern,Western Europe,Europe,46.8182,8.2275,4000,12700,39516,22000,2000,9000000,9.09,NaN
33,New Zealand,New Zealand,New Zealand Dollar,Wellington,Australia and New Zealand,Oceania,-40.9006,174.8860,123000,107000,263310,190000,5000,5290000,9.61,Christopher Luxon
34,Singapore,Republic of Singapore,Singapore Dollar,Singapore,South-eastern Asia,Asia,1.3521,103.8198,7,2,718,0,718,6040000,6.48,Lawrence Wong
35,Nepal,Federal Democratic Republic of Nepal,Nepalese Rupee,Kathmandu,Southern Asia,Asia,28.3949,84.1240,41000,59300,143350,110000,3000,29600000,6.48,K. P. Sharma Oli
36,Bangladesh,People's Republic of Bangladesh,Bangladeshi Taka,Dhaka,Southern Asia,Asia,23.6850,90.3563,83000,14500,130170,88000,4000,175700000,4.60,NaN
37,Sri Lanka,Democratic Socialist Republic of Sri Lanka,Sri Lankan Rupee,Sri Jayawardenepura Kotte,Southern Asia,Asia,7.8731,80.7718,27500,19200,62710,40000,2500,21900000,6.19,Anura Kumara Dissanayake
38,Pakistan,Islamic Republic of Pakistan,Pakistani Rupee,Islamabad,Southern Asia,Asia,30.3753,69.3451,362000,26600,770880,620000,18000,255220000,4.12,Shehbaz Sharif

In [5]:
df.shape

(39, 16)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   country           39 non-null     str
 1   countrylong       39 non-null     str
 2   currency          39 non-null     str
 3   capital city      39 non-null     str
 4   region            39 non-null     str
 5   continent         39 non-null     str
 6   latitude          39 non-null     float64
 7   longitude         39 non-null     float64
 8   agriculture land  39 non-null     int64
 9   forestarea        39 non-null     int64
 10  land ares         39 non-null     int64
 11  rural land        39 non-null     int64
 12  urban land        39 non-null     int64
 13  population        39 non-null     int64
 14  democratic score  39 non-null     float64
 15  political leader  36 non-null     str
dtypes: float64(3), int64(6), str(7)
memory usage: 8.3 KB

In [7]:
df.describe()

,latitude,longitude,agriculture land,forestarea,land ares,rural land,urban land,population,democratic score
count,39.000000,39.000000,3.900000e+01,3.900000e+01,3.900000e+01,3.900000e+01,39.000000,3.900000e+01,39.000000
mean,25.314926,39.256410,7.834238e+05,7.602918e+05,2.129776e+06,1.642328e+06,53551.743590,1.540147e+08,6.497949
std,27.527791,67.541091,1.280785e+06,1.623036e+06,3.666312e+06,2.837028e+06,84864.191057,3.101074e+08,2.169767
min,-40.900600,-106.346800,7.000000e+00,2.000000e+00,7.180000e+02,0.000000e+00,718.000000,5.290000e+06,2.080000
25%,11.570150,6.759400,4.235000e+04,4.735000e+04,2.787250e+05,1.750000e+05,5500.000000,3.205000e+07,4.820000
50%,30.375300,31.165600,2.210000e+05,1.490000e+05,5.108900e+05,3.500000e+05,15000.000000,5.890000e+07,6.490000
75%,46.522900,95.674400,8.265000e+05,4.865000e+05,1.910734e+06,1.340000e+06,47500.000000,1.276234e+08,8.200000
max,61.524000,174.886000,5.280000e+06,8.150000e+06,1.637687e+07,1.220000e+07,300000.000000,1.438070e+09,9.810000

In [ ]:
#which country has the highest population

In [10]:
df[df['population']==df['population'].max()]['country']

0    India
Name: country, dtype: str

In [11]:
#what is the capital of the country with highest population

In [15]:
df[df["population"]==df['population'].max()]['capital city']

0    New Delhi
Name: capital city, dtype: str

In [16]:
#which country has minimum population

In [17]:
df[df["population"]==df["population"].min()]['country']

33    New Zealand
Name: country, dtype: str

In [18]:
#what is the capital of the country with least population

In [19]:
df[df["population"]==df['population'].min()]['capital city']

33    Wellington
Name: capital city, dtype: str

In [20]:
#give me the countries with top 5 democratic score

In [25]:
df.sort_values(by='democratic score',ascending=False,inplace=True)
df

,country,countrylong,currency,capital city,region,continent,latitude,longitude,agriculture land,forestarea,land ares,rural land,urban land,population,democratic score,political leader
31,Norway,Kingdom of Norway,Norwegian Krone,Oslo,Northern Europe,Europe,60.4720,8.4689,11300,121000,364270,290000,5000,5600000,9.81,Jonas Gahr Støre
33,New Zealand,New Zealand,New Zealand Dollar,Wellington,Australia and New Zealand,Oceania,-40.9006,174.8860,123000,107000,263310,190000,5000,5290000,9.61,Christopher Luxon
30,Sweden,Kingdom of Sweden,Swedish Krona,Stockholm,Northern Europe,Europe,60.1282,18.6435,26500,280000,407284,330000,7000,10600000,9.39,Ulf Kristersson
32,Switzerland,Swiss Confederation,Swiss Franc,Bern,Western Europe,Europe,46.8182,8.2275,4000,12700,39516,22000,2000,9000000,9.09,NaN
29,Netherlands,Kingdom of the Netherlands,Euro,Amsterdam,Western Europe,Europe,52.1326,5.2913,18100,3700,33670,16000,1500,17900000,8.89,Dick Schoof
2,Canada,Canada,Canadian Dollar,Ottawa,Northern America,North America,56.1304,-106.3468,517900,3470000,9093510,8080000,160000,40105275,8.69,Mark Carney
5,Germany,Federal Republic of Germany,Euro,Berlin,Western Europe,Europe,51.1657,10.4515,165000,114000,348560,210000,26000,83500000,8.68,Friedrich Merz
11,Australia,Commonwealth of Australia,Australian Dollar,Canberra,Australia and New Zealand,Oceania,-25.2744,133.7751,3630000,1340000,7682300,6400000,220000,27230000,8.66,Anthony Albanese
12,Japan,Japan,Japanese Yen,Tokyo,Eastern Asia,Asia,36.2048,138.2529,43700,249000,364500,250000,13000,123300000,8.33,Shigeru Ishiba
3,United Kingdom,United Kingdom of Great Britain and Northern I...,Pound Sterling,London,Northern Europe,Europe,55.3781,-3.4360,172000,317000,241930,160000,19000,69226000,8.31,Keir Starmer
13,South Korea,Republic of Korea,South Korean Won,Seoul,Eastern Asia,Asia,35.9078,127.7669,16400,62900,97600,54000,9000,51710000,8.09,NaN
7,Spain,Kingdom of Spain,Euro,Madrid,Southern Europe,Europe,40.4637,-3.7492,238000,185000,499556,250000,15000,49000000,8.07,Pedro Sánchez
4,France,French Republic,Euro,Paris,Western Europe,Europe,46.2276,2.2137,287000,172000,547557,310000,28000,66650000,8.07,Emmanuel Macron
28,Poland,Republic of Poland,Polish Zloty,Warsaw,Eastern Europe,Europe,51.9194,19.1451,180000,95000,311888,200000,16000,36600000,8.00,Donald Tusk
1,United States,United States of America,US Dollar,"Washington, D.C.",Northern America,North America,37.0902,-95.7129,4076730,3100950,9147420,6740000,268000,340110988,7.85,Donald Trump
6,Italy,Italian Republic,Euro,Rome,Southern Europe,Europe,41.8719,12.5674,124000,95000,294140,145000,12000,58900000,7.69,Giorgia Meloni
0,India,Republic of India,Indian Rupee,New Delhi,Southern Asia,Asia,20.5937,78.9629,2973190,720160,2973190,2090800,88300,1438069596,7.18,Narendra Modi
20,South Africa,Republic of South Africa,South African Rand,Pretoria,Southern Africa,Africa,-30.5595,22.9375,963000,289000,1213090,1030000,25000,64007000,7.05,Cyril Ramaphosa
10,Argentina,Argentine Republic,Argentine Peso,Buenos Aires,South America,South America,-38.4161,-63.6167,1080000,945000,2736690,2050000,100000,45851000,6.62,Javier Milei
8,Brazil,Federative Republic of Brazil,Brazilian Real,Brasília,South America,South America,-14.2350,-51.9253,2820000,4966200,8358140,6890000,300000,212583750,6.49,Luiz Inácio Lula da Silva
34,Singapore,Republic of Singapore,Singapore Dollar,Singapore,South-eastern Asia,Asia,1.3521,103.8198,7,2,718,0,718,6040000,6.48,Lawrence Wong
35,Nepal,Federal Democratic Republic of Nepal,Nepalese Rupee,Kathmandu,Southern Asia,Asia,28.3949,84.1240,41000,59300,143350,110000,3000,29600000,6.48,K. P. Sharma Oli
15,Indonesia,Republic of Indonesia,Indonesian Rupiah,Jakarta,South-eastern Asia,Asia,-0.7893,113.9213,1560000,921000,1877519,1240000,65000,283500000,6.44,Prabowo Subianto
16,Thailand,Kingdom of Thailand,Thai Baht,Bangkok,South-eastern Asia,Asia,15.8700,100.9925,221000,163000,510890,350000,22000,71620000,6.32,Paetongtarn Shinawatra
37,Sri Lanka,Democratic Socialist Republic of Sri Lanka,Sri Lankan Rupee,Sri Jayawardenepura Kotte,Southern Asia,Asia,7.8731,80.7718,27500,19200,62710,40000,2500,21900000,6.19,Anura Kumara Dissanayake
23,Kenya,Republic of Kenya,Kenyan Shilling,Nairobi,Eastern Africa,Africa,-0.0236,37.9062,276000,37700,569140,460000,13000,56433000,5.88,William Ruto
27,Ukraine,Ukraine,Ukrainian Hryvnia,Kyiv,Eastern Europe,Europe,48.3794,31.1656,413000,96700,579320,400000,12000,38000000,5.73,Volodymyr Zelenskyy
9,Mexico,United Mexican States,Mexican Peso,Mexico City,Central America,North America,23.6345,-102.5528,963000,656000,1943950,1440000,95000,131946900,5.73,Claudia Sheinbaum
24,Morocco,Kingdom of Morocco,Moroccan Dirham,Rabat,Northern Africa,Africa,31.7917,-7.0926,300000,57000,446300,350000,10000,38380000,5.04,Aziz Akhannouch
36,Bangladesh,People's Republic of Bangladesh,Bangladeshi Taka,Dhaka,Southern Asia,Asia,23.6850,90.3563,83000,14500,130170,88000,4000,175700000,4.60,NaN
22,Nigeria,Federal Republic of Nigeria,Nigerian Naira,Abuja,Western Africa,Africa,9.0820,8.6753,690000,232000,910770,730000,20000,237528000,4.44,Bola Tinubu
25,Turkey,Republic of Türkiye,Turkish Lira,Ankara,Western Asia,Asia,38.9637,35.2433,386000,223000,769630,580000,30000,87770000,4.33,Recep Tayyip Erdoğan
38,Pakistan,Islamic Republic of Pakistan,Pakistani Rupee,Islamabad,Southern Asia,Asia,30.3753,69.3451,362000,26600,770880,620000,18000,255220000,4.12,Shehbaz Sharif
17,Vietnam,Socialist Republic of Viet Nam,Vietnamese Dong,Hanoi,South-eastern Asia,Asia,14.0583,108.2772,123000,149000,310070,190000,10000,101300000,3.08,Tô Lâm
19,United Arab Emirates,United Arab Emirates,UAE Dirham,Abu Dhabi,Western Asia,Asia,23.4241,53.8478,4200,300,71020,65000,2500,11294000,3.05,Mohamed bin Zayed Al Nahyan
21,Egypt,Arab Republic of Egypt,Egyptian Pound,Cairo,Northern Africa,Africa,26.8206,30.8025,31000,700,995450,940000,5000,118370000,2.98,Abdel Fattah el-Sisi
14,China,People's Republic of China,Chinese Yuan,Beijing,Eastern Asia,Asia,35.8617,104.1954,5280000,2190000,9424700,6500000,300000,1408280000,2.94,Xi Jinping
26,Russia,Russian Federation,Russian Ruble,Moscow,Eastern Europe,Europe,61.5240,105.3188,2150000,8150000,16376870,12200000,150000,143957000,2.94,Vladimir Putin
18,Saudi Arabia,Kingdom of Saudi Arabia,Saudi Riyal,Riyadh,Western Asia,Asia,23.8859,45.0792,173000,9770,2149690,2040000,6000,34500000,2.08,Mohammed bin Salman

In [28]:
df['country'].head()

31         Norway
33    New Zealand
30         Sweden
32    Switzerland
29    Netherlands
Name: country, dtype: str

In [29]:
#how many total regions are there

In [33]:
df['region'].value_counts().count()

np.int64(16)

In [34]:
#how many countries lie in eartern europe region

In [38]:
df[df['region']=='Eastern Europe']['country']

28     Poland
27    Ukraine
26     Russia
Name: country, dtype: str

In [39]:
#who is the political leader of second largest populated country

In [42]:
df[df['population']==df['population'].nlargest(2).iloc[1]]['political leader']

14    Xi Jinping
Name: political leader, dtype: str

In [43]:
#how many countries are there whose political leaders are unknown

In [49]:
df[df['political leader'].isna()]['country'].count()

np.int64(3)

In [55]:
#how many countriees have republic in full name

In [58]:
count=0
def counting(txt):
    global count
    if 'republic' in txt.lower():
        count+=1
    return txt
df['countrylong']=df['countrylong'].apply(counting)
print(count)

21

In [59]:
#which country in african region has highest population

In [68]:
africa=df[df['continent']=='africa']
africa[africa['population']==africa['population'].max()]['country']

Series([], Name: country, dtype: str)